# Generated by Django 3.0.8 on 2020-07-31 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(db_column='BookID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=45, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=45, null=True)),
                ('author', models.CharField(blank=True, db_column='Author', max_length=45, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('cover_picture', models.CharField(blank=True, db_column='Cover picture', max_length=45, null=True)),
                ('year', models.CharField(blank=True, db_column='Year', max_length=45, null=True)),
                ('link', models.CharField(blank=True, max_length=45, null=True)),
                ('img', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.FloatField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(max_length=100, null=True)),
                ('day', models.CharField(max_length=20, null=True)),
                ('year', models.CharField(max_length=20, null=True)),
                ('cvc', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grandtotal', models.CharField(blank=True, db_column='grandTotal', max_length=45, null=True)),
                ('orderdatetime', models.CharField(blank=True, db_column='orderDateTime', max_length=45, null=True)),
                ('cardid', models.ForeignKey(blank=True, db_column='cardID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.CreditCard')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promoid', models.IntegerField(db_column='PromoID', primary_key=True, serialize=False)),
                ('startdate', models.CharField(blank=True, db_column='StartDate', max_length=45, null=True)),
                ('enddate', models.CharField(blank=True, db_column='EndDate', max_length=45, null=True)),
                ('discount', models.CharField(blank=True, db_column='Discount', max_length=45, null=True)),
                ('promoCode', models.CharField(blank=True, db_column='PromoCode', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usertypes',
            fields=[
                ('usertypeid', models.IntegerField(db_column='UserTypeID', primary_key=True, serialize=False)),
                ('usertypename', models.CharField(blank=True, db_column='UserTypeName', max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('promotion', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('bookid', models.ForeignKey(blank=True, db_column='bookID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Book')),
                ('orderid', models.ForeignKey(blank=True, db_column='orderID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=True, null=True)),
                ('promoApplied', models.BooleanField(default=False)),
                ('promoCode', models.CharField(blank=True, db_column='PromoCode', default=False, max_length=10, null=True)),
                ('cartid', models.ForeignKey(db_column='CartsId', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Carts')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Users'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.IntegerField(db_column='orderID', primary_key=True, serialize=False)),
                ('grandtotal', models.CharField(blank=True, db_column='grandTotal', max_length=45, null=True)),
                ('orderdatetime', models.CharField(blank=True, db_column='orderDateTime', max_length=45, null=True)),
                ('cardid', models.ForeignKey(blank=True, db_column='cardID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.CreditCard')),
                ('promoid', models.ForeignKey(blank=True, db_column='promoID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Promotion')),
                ('userid', models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Inventbookid',
            fields=[
                ('idinventbookid', models.IntegerField(db_column='idInventBookID', primary_key=True, serialize=False)),
                ('quantityonhand', models.IntegerField(blank=True, db_column='QuantityOnHand', null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.CharField(blank=True, max_length=45, null=True)),
                ('bookidfk', models.ForeignKey(blank=True, db_column='BookIdFK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Book')),
            ],
        ),
        migrations.AddField(
            model_name='creditcard',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Users'),
        ),
        migrations.AddField(
            model_name='carts',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Users'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', max_length=20, null=True)),
                ('orderstatus', models.BooleanField(default=False)),
                ('bookid', models.ForeignKey(blank=True, db_column='bookID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Book')),
                ('cartid', models.ForeignKey(db_column='CartsId', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Carts')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=100, null=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Users')),
            ],
        ),
    ]
